export type AgentKey = "TIME_TRACKING" | "PROJECT_PROGRESS";

export type AgentCapabilityKey =
  | "START_WORK_SESSION"
  | "UPDATE_WORK_SESSION_NOTES"
  | "PAUSE_WORK_SESSION"
  | "RESUME_WORK_SESSION"
  | "FINISH_WORK_SESSION"
  | "CREATE_TIME_ENTRY_SUGGESTION"
  | "CREATE_TIME_ENTRY"
  | "START_WORKSTREAM"
  | "FINISH_WORKSTREAM"
  | "REOPEN_WORKSTREAM"
  | "CHANGE_WORKSTREAM_VISIBILITY"
  | "COMPLETE_EVENT"
  | "REOPEN_EVENT"
  | "CHANGE_EVENT_VISIBILITY"
  | "MOVE_COMPLETED_ITEMS_TO_DETAILED"
  | "GENERATE_ACCOMPLISHMENTS_SINCE_REPORT";

export type AgentApprovalMode =
  | "AUTO_APPLY_DISABLED"
  | "MANUAL_APPROVAL"
  | "DELEGATED_APPROVAL";

export type AgentStatusScopeCode =
  | "AGENT_INSTRUCTION"
  | "AGENT_SUGGESTION"
  | "AGENT_APPROVAL"
  | "WORK_SESSION";

export type AgentSuggestionType =
  | "CREATE_TIME_ENTRY"
  | "UPDATE_PROGRESS"
  | "UPDATE_VISIBILITY"
  | "GENERATE_REPORTING_NARRATIVE"
  | "ASK_CLARIFICATION"
  | "NO_ACTION";

export type AgentTargetEntity =
  | "TIME_ENTRY"
  | "WORK_SESSION"
  | "PROJECT"
  | "PROJECT_WORKSTREAM"
  | "PROJECT_EVENT"
  | "PROJECT_TASK"
  | "RISK"
  | "RISK_ACTION"
  | "DECISION"
  | "REPORTING_PACK";

export type AgentActionType =
  | "INSTRUCTION_CREATED"
  | "INSTRUCTION_PROCESSED"
  | "SUGGESTION_CREATED"
  | "SUGGESTION_APPROVED"
  | "SUGGESTION_REJECTED"
  | "SUGGESTION_APPLIED"
  | "WORK_SESSION_STARTED"
  | "WORK_SESSION_NOTES_UPDATED"
  | "WORK_SESSION_PAUSED"
  | "WORK_SESSION_RESUMED"
  | "WORK_SESSION_FINISHED"
  | "WORK_SESSION_CANCELLED"
  | "TIME_ENTRY_CREATED"
  | "PROJECT_PROGRESS_SUGGESTION_CREATED"
  | "PROJECT_PROGRESS_SUGGESTION_APPLIED";

export type AgentJsonValue =
  | string
  | number
  | boolean
  | null
  | AgentJsonValue[]
  | { [key: string]: AgentJsonValue };
