export const STATUS_AREAS = {
  DECISION: "DECISION",
  PROJECT: "PROJECT",
  RISK: "RISK",
  RISK_ACTION: "RISK_ACTION",
  AGENT_INSTRUCTION: "AGENT_INSTRUCTION",
  AGENT_SUGGESTION: "AGENT_SUGGESTION",
  AGENT_APPROVAL: "AGENT_APPROVAL",
  WORK_SESSION: "WORK_SESSION",
} as const;
